'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [isMenuOpen, setMenuOpen] = useState(false);

  const toggleMenu = () => {
    setMenuOpen(!isMenuOpen);
  };
  return (
    <html lang="en">
      <body className={inter.className + ' content-grid'}>
      <nav className={`full-width ${isMenuOpen ? 'menu-open' : ''}`}>
      <div className="nav">
        <h3>
          <div className="wrapper">
            <svg>
              <text x="50%" y="50%" dy=".35em" textAnchor="middle">
                Smail Abd El Madjid
              </text>
            </svg>
          </div>
        </h3>
        <div className="burger-menu" onClick={toggleMenu}>
          <div className="burger-icon"></div>
          <div className="burger-icon"></div>
          <div className="burger-icon"></div>
        </div>
        <ul className={isMenuOpen ? 'open' : ''}>
          <li>Home</li>
          <li>Experience</li>
          <li>Project</li>
          <li>Skills</li>
          <li>Contact</li>
        </ul>
      </div>
      <div className="menu-overlay" onClick={toggleMenu}></div>
    </nav>
        
        
        {children}
        </body>
    </html>
  )
}
